// Product data for SecondChapter Books (Secondhand Bookstore)

const products = [
  {
    id: 1,
    name: 'To Kill a Mockingbird',
    price: 8.99,
    category: 'Fiction',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
    discount: 0,
    isNew: false,
    rating: 4.8,
    reviews: 42,
    featured: true,
    description: 'Harper Lee\'s classic novel in good condition with minor wear on the cover.'
  },
  {
    id: 2,
    name: '1984',
    price: 7.99,
    category: 'Fiction',
    image: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19',
    discount: 10,
    isNew: false,
    rating: 4.6,
    reviews: 38,
    featured: true,
    description: 'George Orwell\'s dystopian masterpiece. This edition has some highlighting and notes.'
  },
  {
    id: 3,
    name: 'The Elements of Style',
    price: 5.99,
    category: 'Non-Fiction',
    image: 'https://images.unsplash.com/photo-1589998059171-988d887df646',
    discount: 0,
    isNew: false,
    rating: 4.5,
    reviews: 29,
    featured: true,
    description: 'Strunk & White\'s concise handbook on English language style. Like new condition.'
  },
  {
    id: 4,
    name: 'Pride and Prejudice',
    price: 6.99,
    category: 'Fiction',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
    discount: 15,
    isNew: false,
    rating: 4.7,
    reviews: 56,
    featured: true,
    description: 'Jane Austen\'s beloved novel. Vintage edition with beautiful cover art.'
  },
  {
    id: 5,
    name: 'A Brief History of Time',
    price: 9.99,
    category: 'Non-Fiction',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765',
    discount: 0,
    isNew: false,
    rating: 4.4,
    reviews: 25,
    featured: false,
    description: 'Stephen Hawking\'s exploration of cosmology. Good condition with intact dust jacket.'
  },
  {
    id: 6,
    name: 'The Hobbit',
    price: 8.50,
    category: 'Fiction',
    image: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf',
    discount: 0,
    isNew: false,
    rating: 4.9,
    reviews: 61,
    featured: false,
    description: 'J.R.R. Tolkien\'s classic adventure. Well-loved copy with some dog-eared pages.'
  },
  {
    id: 7,
    name: 'Sapiens: A Brief History of Humankind',
    price: 12.99,
    category: 'Non-Fiction',
    image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73',
    discount: 20,
    isNew: true,
    rating: 4.8,
    reviews: 47,
    featured: false,
    description: 'Yuval Noah Harari\'s bestseller. Nearly new condition, only read once.'
  },
  {
    id: 8,
    name: 'The Great Gatsby',
    price: 6.50,
    category: 'Fiction',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f',
    discount: 0,
    isNew: false,
    rating: 4.5,
    reviews: 35,
    featured: false,
    description: 'F. Scott Fitzgerald\'s masterpiece. Vintage paperback with some yellowing but fully intact.'
  },
  {
    id: 9,
    name: 'The Art of War',
    price: 7.99,
    category: 'Philosophy',
    image: 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc',
    discount: 5,
    isNew: false,
    rating: 4.6,
    reviews: 31,
    featured: false,
    description: 'Sun Tzu\'s ancient military treatise. Hardcover edition with original notes and commentary.'
  },
  {
    id: 10,
    name: 'The Catcher in the Rye',
    price: 6.99,
    category: 'Fiction',
    image: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19',
    discount: 0,
    isNew: false,
    rating: 4.3,
    reviews: 28,
    featured: false,
    description: 'J.D. Salinger\'s coming-of-age novel. Paperback with some creasing on the spine.'
  },
  {
    id: 11,
    name: 'Thinking, Fast and Slow',
    price: 11.99,
    category: 'Psychology',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765',
    discount: 0,
    isNew: true,
    rating: 4.7,
    reviews: 39,
    featured: false,
    description: 'Daniel Kahneman\'s exploration of the two systems of thinking. Like-new condition.'
  },
  {
    id: 12,
    name: 'Brave New World',
    price: 7.50,
    category: 'Fiction',
    image: 'https://images.unsplash.com/photo-1551029506-0807df4e2031',
    discount: 10,
    isNew: false,
    rating: 4.5,
    reviews: 27,
    featured: false,
    description: 'Aldous Huxley\'s dystopian novel. Annotated edition with some highlighting.'
  }
];